# Generated by Django 6.0.6 on 2026-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('escrow_refund', 'Escrow and Refund Policy'), ('lister_onboarding', 'Lister Onboarding Agreement')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('content', models.TextField(help_text='Paste plain text. Leave a blank line between paragraphs.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
