# Generated by Django 6.0.6 on 2026-06-17 21:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('self-contain', 'Self Contain'), ('single room', 'Single Room'), ('shared room', 'Shared Room'), ('shared apartment', 'Shared Apartment')], max_length=20)),
                ('rooms_available', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000)])),
                ('cover_image', models.ImageField(upload_to='listings/images/')),
                ('video', models.FileField(blank=True, upload_to='listings/videos/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.listing')),
                ('has_water', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_bathroom', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_fence', models.BooleanField(default=False)),
                ('has_prepaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.listing')),
                ('str_address', models.CharField(max_length=120)),
                ('distance_desc', models.TextField(blank=True, help_text='e.g. 5 minute walk to the Main Gate...')),
            ],
        ),
    ]
