# Generated by Django 6.0.6 on 2026-06-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_cover_image_remove_listing_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='cover_image',
            new_name='image',
        ),
    ]
