# Generated by Django 6.0.6 on 2026-06-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_cover_image_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='listings/videos/'),
        ),
    ]
