# Generated by Django 6.0.6 on 2026-07-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingflag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='agent',
            new_name='lister',
        ),
    ]
