# Generated by Django 6.0.6 on 2026-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_agent_listing_lister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('self-contain', 'Self Contain'), ('single-room', 'Single Room'), ('shared-room', 'Shared Room'), ('shared-apartment', 'Shared Apartment'), ('2-bedroom', '2 Bedroom'), ('3-bedroom', '3 Bedroom')], max_length=30),
        ),
    ]
