# Generated by Django 6.0.6 on 2026-07-20 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='listings/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])]),
        ),
    ]
