# Generated by Django 6.0.6 on 2026-07-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_dob_customuser_phone_number_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile',
            new_name='user',
        ),
    ]
