# Generated by Django 6.0.6 on 2026-07-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profile_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=10),
        ),
    ]
