# Generated by Django 6.0.6 on 2026-07-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('lister', 'Lister'), ('seeker', 'Seeker')], max_length=10),
        ),
    ]
