# Generated by Django 6.0.6 on 2026-07-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_agreed_to_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreed_to_lister_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agreed_to_lister_onboarding_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lister_onboarding_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
